version: '3.1'

services:

  wordpress:
    # use latest tag or specify version
    image: wordpress:4.9.8-php7.2-apache
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ${PWD}/docker-compose-collections/woocommerce/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - wordpress:/var/www/html

  db:
    # use latest or specify version
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_INITDB_SKIP_TZINFO: 'true'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
