version: '3.1'

services:

  wordpress:
    # use latest tag or specify version
    image: bitnami/wordpress-nginx:4.9.8
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      - MARIADB_HOST=db
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - wordpress:/bitnami/wordpress

  db:
    # use latest or specify version
    image: bitnami/mariadb:10.3
    restart: always
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db:/bitnami/mariadb

volumes:
  wordpress:
  db:
